### ISSUE TITLE
AuctionatorData addon installs on Classic Era and Cataclysm Classic with #Interface: 110000

### ISSUE THREAD

**Issue by b-morgan** [Auctionator/auctionator-app-bugs#1]
**Describe the bug**
AuctionatorData addon installs on Classic Era and Cataclysm Classic with #Interface: 110000

**To Reproduce**
1. Install the App

**Expected behavior**
Proper "#Interface:" value for the WoW version

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 24

**Additional context**

**Logs**
(you can find these in your user data directory)
I'd be happy to include logs if I knew where the "user data directory" was.

**Comment by b-morgan** [comment]
I used `## Interface: 11502, 11503, 20504, 30403, 40400, 100207, 110000, 110002` which I copied from another addon.

**Comment by jrob8577** [comment]
Resolved in 1.0.25
