### ISSUE TITLE
Two realms with same name on different editions of WoW only one shows up

### ISSUE THREAD

**Issue by b-morgan** [Auctionator/auctionator-app-bugs#14]
**Describe the bug**
On Cataclysm Classic, I have toons on Mankrik and Whitemane. On Classic Era, I have toons on the Seasonal realm Wild Growth and on the Classic Era realm Whitemane. Both realms show on Cataclysm Classic, Only Wild Growth shows up on Classic Era.

**Screenshots**
![image](https://github.com/user-attachments/assets/69547de5-d0fe-4e0d-b1f0-66abe3292b57)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 27

**Additional context**

**Logs**
Please attach the most recent logs (you can find these in your user data directory - go to the application menu, and select "open logs folder")
[main.log](https://github.com/user-attachments/files/16702863/main.log)

**Comment by jrob8577** [comment]
28 released
