### ISSUE TITLE
Lua error on 11.0.0 login - attempt to index field 'a' (a nil value)

### ISSUE THREAD

**Issue by b-morgan** [Auctionator/auctionator-app-bugs#3]
**Describe the bug**
Lua error on logging in (see Additional context below)

**To Reproduce**
1. Login

**Expected behavior**
Error free login

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 24

**Additional context**
1x AuctionatorData/merge.lua:46: attempt to index field 'a' (a nil value)
[string "@AuctionatorData/merge.lua"]:46: in function <AuctionatorData/merge.lua:10>

Locals:
root = "Anvilmar"
id = "71"
data = <table> {
 76078 = <table> {
 }
 33867 = <table> {
 }
 40023 = <table> {
 }
 10023 = <table> {
 }
 36078 = <table> {
 }
 166815 = <table> {
 }
 p:1151 = <table> {
 }
 p:1511:25 = <table> {
 }
 p:125:1:2 = <table> {
 }
 15300 = <table> {
 }
 25300 = <table> {
 }
 24047 = <table> {
 }
 14047 = <table> {
 }
 161966 = <table> {
 }
 184100 = <table> {
 }
 106749 = <table> {
 }
 15408 = <table> {
 }
 42408 = <table> {
 }
 75078 = <table> {
 }
 38645 = <table> {
 }
 18645 = <table> {
 }
 11023 = <table> {
 }
 158777 = <table> {
 }
 163522 = <table> {
 }
 187915 = <table> {
 }
 18661 = <table> {
 }
 118877 = <table> {
 }
 p:2585 = <table> {
 }
 167967 = <table> {
 }
 115464 = <table> {
 }
 15078 = <table> {
 }
 25078 = <table> {
 }
 159609 = <table> {
 }
 12408 = <table> {
 }
 13464 = <table> {
 }
 10009 = <table> {
 }
 40009 = <table> {
 }
 128843 = <table> {
 }
 47645 = <table> {
 }
 43464 = <table> {
 }
 93464 = <table> {
 }
 172438 = <table> {
 }
 188948 = <table> {
 }
 10235 = <table> {
 }
 p:2692:1 = <table> {
 }
 p:2891:1:2 = <table> {
 }
 94047 = <table> {
 }
 14464 = <table> {
 }
 159845 = <table> {
 }
 44464 = <table> {
 }
 164515 = <table> {
 }
 31235 = <table> {
 }
 116677 = <table> {
 }
 p:2466:4:3 = <table> {
 }
 p:3178:25 = <table> {
 }
 78300 = <table> {
 }
 18300 = <table> {
 }
 15123 = <table> {
 }
 25123 = <table> {
 }
 p:2086:1 = <table> {
 }
 116260 = <table> {
 }
 p:162:2:3 = <table> {
 }
 75123 = <table> {
 }
 p:2407:25 = <table> {
 }
 15661 = <table> {
 }
 25661 = <table> {
 }
 p:198:1:3 = <table> {
 }
 p:2556:8 = <table> {
 }
 194968 = <table> {
 }
 52078 = <table> {
 }
 13000 = <table> {
 }
 82078 = <table> {
 }
 55661 = <table> {
 }
 43000 = <table> {
 }
 210114 = <table> {
 }
 p:116:25:3 = <table> {
 }
 203412 = <table> {
 }
 116614 = <table> {
 }
 p:1183:1 = <table> {
 }
 24661 = <table> {
 }
 14661 = <table> {
 }
 98867 = <table> {
 }
 153664 = <table> {
 }
 37743 = <table> {
 }
 74661 = <table> {
 }
 p:2080:25 = <table> {
 }
 p:2697:1 = <table> {
 }
 31216 = <table> {
 }
 166804 = <table> {
 }
 220314 = <table> {
 }
 174327 = <table> {
 }
 p:3171:25:3 = <table> {
 }
 165518 = <table> {
 }
 194857 = <table> {
 }
 27661 = <table> {
 }
 47626 = <table> {
 }
 82023 = <table> {
 }
 12023 = <table> {
 }
 21867 = <table> {
 }
 31867 = <table> {
 }
 142266 = <table> {
 }
 116804 = <table> {
 }
 44078 = <table> {
 }
 40216 = <table> {
 }
 10216 = <table> {
 }
 14235 = <table> {
 }
 77536 = <table> {
 }
 199977 = <table> {
 }
 p:1345 = <table> {
 }
 p:3512 = <table> {
 }
 164327 = <table> {
 }
 21177 = <table> {
 }
 31177 = <table> {
 }
 56047 = <table> {
 }
 169132 = <table> {
 }
 159167 = <table> {
 }
 p:1966 = <table> {
 }
 p:2438 = <table> {
 }
 76661 = <table> {
 }
 15235 = <table> {
 }
 25235 = <table> {
 }
 179369 = <table> {
 }
 198328 = <table> {
 }
 67047 = <table> {
 }
 173074 = <table> {
 }
 p:1245 = <table> {
 }
 p:2704 = <table> {
 }
 112164 = <table> {
 }
 46009 = <table> {
 }
 36009 = <table> {
 }
 203860 = <table> {
 }
 p:138:25:3 = <table> {
 }
 87429 = <table> {
 }
 29536 = <table> {
 }
 191398 = <table> {
 }
 24834 = <table> {
 }
 109126 = <table> {
 }
 14834 = <table> {
 }
 121189 = <table> {
 }
 74834 = <table> {
 }
 54834 = <table> {
 }
 p:3516:25 = <table> {
 }
 p:1540:25:3 = <table> {
 }
 195359 = <table> {
 }
 27429 = <table> {
 }
 p:195:25 = <table> {
 }
 15009 = <table> {
 }
 25009 = <table> {
 }
 24822 = <table> {
 }
 34822 = <table> {
 }
 44822 = <table> {
 }
 38429 = <table> {
 }
 74822 = <table> {
 }
 159897 = <table> {
 }
 p:3224:25 = <table> {
 }
 24743 = <table> {
 }
 14743 = <table> {
 }
 14429 = <table> {
 }
 43661 = <table> {
 }
 p:117:3:2 = <table> {
 }
 p:67:2 = <table> {
 }
 159477 = <table> {
 }
 112498 = <table> {
 }
 173129 = <table> {
 }
 55429 = <table> {
 }
 204963 = <table> {
 }
 190953 = <table> {
 }
 15743 = <table> {
 }
 18504 = <table> {
 }
 22661 = <table> {
 }
 25429 = <table> {
 }
 15429 = <table> {
 }
 55743 = <table> {
 }
 194789 = <table> {
 }
 36429 = <table> {
 }
 60388 = <table> {
 }
 152638 = <table> {
 }
 10388

**Logs**
[main.zip](https://github.com/user-attachments/files/16589576/main.zip)

**Comment by jrob8577** [comment]
I _think_ this will be fixed by some changes in how we handle the writing and import of files. Will keep this open until we can verify.

**Comment by jrob8577** [comment]
@b-morgan just wanted check in to see if you had had an opportunity to test this again

**Comment by b-morgan** [comment]
No. This close to a major release, I don't check "Load out of date Addons" and AuctionatorData is out of date.

**Comment by b-morgan** [comment]
With 1.0.26, this error is replaced with the error in issue #6.

**Comment by jrob8577** [comment]
Tracking in #6
