### ISSUE TITLE
Classic Era realms incomplete

### ISSUE THREAD

**Issue by b-morgan** [Auctionator/auctionator-app-bugs#4]
**Describe the bug**
On Classic Era, I have toons (3) on the Seasonal realm Wild Growth and on the Classic Era realm Whitemane (5 toons). Only Wild Growth shows up.

**Screenshots**
![image](https://github.com/user-attachments/assets/69547de5-d0fe-4e0d-b1f0-66abe3292b57)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 25 (also failed on 24)

**Additional context**

**Logs**
Please attach the most recent logs (you can find these in your user data directory - go to the application menu, and select "open logs folder")
[main.log](https://github.com/user-attachments/files/16603040/main.log)

**Comment by b-morgan** [comment]
The retail realms have an issue as well.

![image](https://github.com/user-attachments/assets/1b5dd98a-034f-4bf0-8700-0f9a30447bb8)

**Comment by jrob8577** [comment]
This is expected; that refers to the `US PS Realm 222` that does not have api data. I'll move the warning to the realm, not sure why I put it there lol.

**Comment by jrob8577** [comment]
Moved the "no realm found" error message to any realm that has no connected realm id (release 1.0.26)
