### ISSUE TITLE
Need a better check for update (and a better update process)

### ISSUE THREAD

**Issue by b-morgan** [Auctionator/auctionator-app-bugs#5]
**Describe the bug**
Need a better check for update.

**Expected behavior**
I believe the intended behavior of the application is to be running all the time, therefore it should check for updates at some reasonable interval (like when it updates the realm data?).

**Desktop (please complete the following information)**
 - OS: Windows 10
 - Version 25

**Comment by jrob8577** [comment]
It should be checking hourly; is this not happening for you?

**Comment by b-morgan** [comment]
Not happening for me... It is 6:31am on 8/16/24 as I write this message...

![image](https://github.com/user-attachments/assets/2a589438-9cd4-44a9-8939-da28e11d650a)

**Comment by b-morgan** [comment]
It is not happening for me. At 6:36am on 8/16/24 I captured the attached screenshot.

![image](https://github.com/user-attachments/assets/49f30409-1982-4f98-bc39-ffede9f81cf3)

[main.zip](https://github.com/user-attachments/files/16637113/main.zip)

**Comment by b-morgan** [comment]
Not only is it not checking hourly, but the application needs to be closed and opened multiple times to actually complete the update.

**Comment by jrob8577** [comment]
Closing; i think this was fixed in 1.0.27, with some enhancements coming out in 1.0.28. Please file a new issue or re-open if the current version is still not behaving.
