### ISSUE TITLE
Log file management

### ISSUE THREAD

**Issue by b-morgan** [Auctionator/auctionator-app-bugs#7]
**Describe the bug**
The log file just grows and grows...

**Desired behavior**
1. When the application is restarted (manually or via an "automatic" update), rename the current log (use the creation time stamp) and open a new one.
2. Add a setting (similar to the Backup Retention) to control how many old logs are retained.
3. (Optional) Compress (zip) the old logs to save space (extra points for keeping the most recent old log uncompressed and compressing the older ones).

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 26

**Additional context**

**Logs**
Please attach the most recent logs (you can find these in your user data directory - go to the application menu, and select "open logs folder")

**Comment by jrob8577** [comment]
Should be completed in 1.0.27. There was a bug where I wasn't correctly deleting files past the retention date, this is fixed in 1.0.28.
